//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_11_AuthorPictures
    {
        public tbl_11_AuthorPictures()
        {
            this.tbl_14_ArtWork = new HashSet<tbl_14_ArtWork>();
        }
    
        public int AuthorPicturesId { get; set; }
        public int GeografyPlaceId { get; set; }
        public int HistoryPeriodId { get; set; }
        public int AuthorTypeId { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string AuthorMiddleName { get; set; }
        public Nullable<System.DateTime> AuthorDate_of_birth { get; set; }
        public Nullable<System.DateTime> AuthorOtherDates { get; set; }
        public string AuthorBiography { get; set; }
    
        public virtual tbl_12_GeografyPlace tbl_12_GeografyPlace { get; set; }
        public virtual tbl_30_AuthorType tbl_30_AuthorType { get; set; }
        public virtual tbl_13_HistoryPeriod tbl_13_HistoryPeriod { get; set; }
        public virtual ICollection<tbl_14_ArtWork> tbl_14_ArtWork { get; set; }
    }
}
