//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_12_GeografyPlace
    {
        public tbl_12_GeografyPlace()
        {
            this.tbl_11_AuthorPictures = new HashSet<tbl_11_AuthorPictures>();
        }
    
        public int GeografyPlaceId { get; set; }
        public int CountryId { get; set; }
        public string GeografyPlaceCity { get; set; }
        public string Administrative_District_1 { get; set; }
        public string Administrative_District_2 { get; set; }
        public string Administrative_District_3 { get; set; }
    
        public virtual ICollection<tbl_11_AuthorPictures> tbl_11_AuthorPictures { get; set; }
        public virtual tbl_15_Country tbl_15_Country { get; set; }
    }
}
