//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_33_ObjectsPhoto
    {
        public int ObjectsPhotoId { get; set; }
        public int FocusSectionId { get; set; }
        public byte[] ObjectsPhotoFile { get; set; }
        public Nullable<System.DateTime> ObjectsPhotoDate { get; set; }
    
        public virtual tbl_32_FocusSection tbl_32_FocusSection { get; set; }
    }
}
