//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_24_CrystalStructuresChE
    {
        public tbl_24_CrystalStructuresChE()
        {
            this.tbl_10_ChemicalElement = new HashSet<tbl_10_ChemicalElement>();
        }
    
        public int CrystalStructureId { get; set; }
        public string CrystalStructureDescription { get; set; }
    
        public virtual ICollection<tbl_10_ChemicalElement> tbl_10_ChemicalElement { get; set; }
    }
}
