//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_6_City
    {
        public tbl_6_City()
        {
            this.tbl_1_User = new HashSet<tbl_1_User>();
        }
    
        public int CityId { get; set; }
        public string UserCity { get; set; }
        public string Country { get; set; }
        public string AdministrativeDevision { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<tbl_1_User> tbl_1_User { get; set; }
    }
}
