//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_10_ChemicalElement
    {
        public tbl_10_ChemicalElement()
        {
            this.tbl_22_Spektr = new HashSet<tbl_22_Spektr>();
            this.tbl_23_StatesOfMatter_ChE = new HashSet<tbl_23_StatesOfMatter_ChE>();
            this.tbl_25_Isotop_ChE = new HashSet<tbl_25_Isotop_ChE>();
            this.tbl_9_SpektrumLinesChE = new HashSet<tbl_9_SpektrumLinesChE>();
        }
    
        public int ChemicalElementId { get; set; }
        public int CrystalStructureId { get; set; }
        public string ChemicalElementName { get; set; }
        public string ChemicalElementDescription { get; set; }
        public Nullable<int> ChemicalElementAtomicNumber { get; set; }
        public Nullable<double> ChemicalElementAtomicWeight { get; set; }
        public Nullable<int> ChemicalElementCore { get; set; }
        public Nullable<int> ChemicalElementIons { get; set; }
    
        public virtual tbl_24_CrystalStructuresChE tbl_24_CrystalStructuresChE { get; set; }
        public virtual ICollection<tbl_22_Spektr> tbl_22_Spektr { get; set; }
        public virtual ICollection<tbl_23_StatesOfMatter_ChE> tbl_23_StatesOfMatter_ChE { get; set; }
        public virtual ICollection<tbl_25_Isotop_ChE> tbl_25_Isotop_ChE { get; set; }
        public virtual ICollection<tbl_9_SpektrumLinesChE> tbl_9_SpektrumLinesChE { get; set; }
    }
}
