//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_1_User
    {
        public tbl_1_User()
        {
            this.tbl_32_FocusSection = new HashSet<tbl_32_FocusSection>();
            this.UserRole = new HashSet<UserRole>();
        }
    
        public int IDUser { get; set; }
        public int OrganizationId { get; set; }
        public int PrivilegeId { get; set; }
        public int CityId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserMiddleName { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserMobilePhoneNumber { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string ActivatedLink { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public string AvatarPath { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual tbl_5_Organization tbl_5_Organization { get; set; }
        public virtual tbl_3_Privileges tbl_3_Privileges { get; set; }
        public virtual tbl_6_City tbl_6_City { get; set; }
        public virtual ICollection<tbl_32_FocusSection> tbl_32_FocusSection { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
