//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_5_Organization
    {
        public tbl_5_Organization()
        {
            this.tbl_1_User = new HashSet<tbl_1_User>();
        }
    
        public int OrganizationId { get; set; }
        public string OrganizationStatus { get; set; }
        public string OrganizationType { get; set; }
        public string OrganizationDescription { get; set; }
        public string OrganizationAdress { get; set; }
        public string OrganizationEmail { get; set; }
        public string OrganizationPhoneNumbe { get; set; }
    
        public virtual ICollection<tbl_1_User> tbl_1_User { get; set; }
    }
}
