//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_32_FocusSection
    {
        public tbl_32_FocusSection()
        {
            this.tbl_22_Spektr = new HashSet<tbl_22_Spektr>();
            this.tbl_33_ObjectsPhoto = new HashSet<tbl_33_ObjectsPhoto>();
            this.tbl_34_Peak = new HashSet<tbl_34_Peak>();
            this.tbl_9_SpektrumLinesChE = new HashSet<tbl_9_SpektrumLinesChE>();
        }
    
        public int FocusSectionId { get; set; }
        public int IDUser { get; set; }
        public int ArtWorkId { get; set; }
        public string FocusSectionName { get; set; }
        public Nullable<System.DateTime> FocusSectionDate { get; set; }
        public Nullable<System.DateTime> FocusSectionTime { get; set; }
        public string FocusSectionSpektrFile { get; set; }
        public string FocusSectionReportFile { get; set; }
        public Nullable<int> LabelFocus { get; set; }
    
        public virtual tbl_1_User tbl_1_User { get; set; }
        public virtual tbl_14_ArtWork tbl_14_ArtWork { get; set; }
        public virtual ICollection<tbl_22_Spektr> tbl_22_Spektr { get; set; }
        public virtual ICollection<tbl_33_ObjectsPhoto> tbl_33_ObjectsPhoto { get; set; }
        public virtual ICollection<tbl_34_Peak> tbl_34_Peak { get; set; }
        public virtual ICollection<tbl_9_SpektrumLinesChE> tbl_9_SpektrumLinesChE { get; set; }
    }
}
