//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_21_SpectrumLine
    {
        public tbl_21_SpectrumLine()
        {
            this.tbl_22_Spektr = new HashSet<tbl_22_Spektr>();
        }
    
        public int SpectrumLineId { get; set; }
        public int LibraryId { get; set; }
        public Nullable<System.DateTime> SpectrumLineDate { get; set; }
        public string SpectrumLinePersonName { get; set; }
        public Nullable<double> SpectrumLineWavelLength { get; set; }
        public string OtherOptions { get; set; }
    
        public virtual tbl_34_LibrarySpectrumLines tbl_34_LibrarySpectrumLines { get; set; }
        public virtual ICollection<tbl_22_Spektr> tbl_22_Spektr { get; set; }
    }
}
