//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_2_Roles
    {
        public tbl_2_Roles()
        {
            this.UserRole = new HashSet<UserRole>();
        }
    
        public int IDRole { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
