//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_39_Metals
    {
        public int MetalId { get; set; }
        public int MaterialId { get; set; }
        public string MetalName { get; set; }
        public string MetalRemark { get; set; }
    
        public virtual tbl_37_Material tbl_37_Material { get; set; }
    }
}
