//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_14_ArtWork
    {
        public tbl_14_ArtWork()
        {
            this.tbl_16_FotoPictures = new HashSet<tbl_16_FotoPictures>();
            this.tbl_17_PassportResearch = new HashSet<tbl_17_PassportResearch>();
            this.tbl_18_RemarkOfDate = new HashSet<tbl_18_RemarkOfDate>();
            this.tbl_32_FocusSection = new HashSet<tbl_32_FocusSection>();
            this.tbl_35_ArtWorkGenre = new HashSet<tbl_35_ArtWorkGenre>();
        }
    
        public int ArtWorkId { get; set; }
        public int AuthorPicturesId { get; set; }
        public int MaterialId { get; set; }
        public int TechnicsId { get; set; }
        public string ArtWorkName { get; set; }
        public string ArtWorkOriginalName { get; set; }
        public string ArtWorkLocation { get; set; }
        public string ArtWorkSize { get; set; }
        public Nullable<System.DateTime> ArtWorkDateResearch { get; set; }
        public string ArtWorkAimResearch { get; set; }
        public string ArtWorkAuthor { get; set; }
        public string ArtWorkAuthor_lang { get; set; }
        public string ArtWorkConclusionNumber { get; set; }
        public Nullable<System.DateTime> ArtWorkCreationDate { get; set; }
        public string ArtWorkStatus { get; set; }
        public string ArtWorkDescription { get; set; }
    
        public virtual tbl_11_AuthorPictures tbl_11_AuthorPictures { get; set; }
        public virtual tbl_36_Technics tbl_36_Technics { get; set; }
        public virtual tbl_37_Material tbl_37_Material { get; set; }
        public virtual ICollection<tbl_16_FotoPictures> tbl_16_FotoPictures { get; set; }
        public virtual ICollection<tbl_17_PassportResearch> tbl_17_PassportResearch { get; set; }
        public virtual ICollection<tbl_18_RemarkOfDate> tbl_18_RemarkOfDate { get; set; }
        public virtual ICollection<tbl_32_FocusSection> tbl_32_FocusSection { get; set; }
        public virtual ICollection<tbl_35_ArtWorkGenre> tbl_35_ArtWorkGenre { get; set; }
    }
}
