//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_9_SpektrumLinesChE
    {
        public int SpektrumLineChEId { get; set; }
        public int ChemicalElementId { get; set; }
        public int FocusSectionId { get; set; }
        public Nullable<double> SpektrumLineChEWavelength { get; set; }
        public Nullable<double> SpektrumLineChEIntensity { get; set; }
    
        public virtual tbl_10_ChemicalElement tbl_10_ChemicalElement { get; set; }
        public virtual tbl_32_FocusSection tbl_32_FocusSection { get; set; }
    }
}
