//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_16_FotoPictures
    {
        public int FotoPicturesId { get; set; }
        public int ArtWorkId { get; set; }
        public byte[] FotoPictures { get; set; }
        public string FotoPicturesObjects { get; set; }
        public string FotoPicturesColors { get; set; }
    
        public virtual tbl_14_ArtWork tbl_14_ArtWork { get; set; }
    }
}
