//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_26_Pigments
    {
        public int PigmentsId { get; set; }
        public int PaintId { get; set; }
        public int GroupId { get; set; }
        public string PigmentColor { get; set; }
        public string PigmentChemicalFormula { get; set; }
        public Nullable<System.DateTime> PigmentYearUsed { get; set; }
        public string PigmentWhereUsed { get; set; }
        public string PigmentLiterature { get; set; }
    
        public virtual tbl_40_Paints tbl_40_Paints { get; set; }
        public virtual tbl_27_Group tbl_27_Group { get; set; }
    }
}
