//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_19_DateOfCreated
    {
        public tbl_19_DateOfCreated()
        {
            this.tbl_18_RemarkOfDate = new HashSet<tbl_18_RemarkOfDate>();
        }
    
        public int DateOfCreatedId { get; set; }
        public Nullable<System.DateTime> DateOfCreated { get; set; }
    
        public virtual ICollection<tbl_18_RemarkOfDate> tbl_18_RemarkOfDate { get; set; }
    }
}
