//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_34_LibrarySpectrumLines
    {
        public tbl_34_LibrarySpectrumLines()
        {
            this.tbl_21_SpectrumLine = new HashSet<tbl_21_SpectrumLine>();
        }
    
        public int LibraryId { get; set; }
        public string LibraryName { get; set; }
        public string LibraryCooment { get; set; }
    
        public virtual ICollection<tbl_21_SpectrumLine> tbl_21_SpectrumLine { get; set; }
    }
}
