//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_36_Technics
    {
        public tbl_36_Technics()
        {
            this.tbl_14_ArtWork = new HashSet<tbl_14_ArtWork>();
        }
    
        public int TechnicsId { get; set; }
        public string TechnicsName { get; set; }
        public string TechnicsRemark { get; set; }
    
        public virtual ICollection<tbl_14_ArtWork> tbl_14_ArtWork { get; set; }
    }
}
