//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_37_Material
    {
        public tbl_37_Material()
        {
            this.tbl_14_ArtWork = new HashSet<tbl_14_ArtWork>();
            this.tbl_22_Spektr = new HashSet<tbl_22_Spektr>();
            this.tbl_38_OtherMaterials = new HashSet<tbl_38_OtherMaterials>();
            this.tbl_39_Metals = new HashSet<tbl_39_Metals>();
            this.tbl_40_Paints = new HashSet<tbl_40_Paints>();
        }
    
        public int MaterialId { get; set; }
        public string MaterialName { get; set; }
    
        public virtual ICollection<tbl_14_ArtWork> tbl_14_ArtWork { get; set; }
        public virtual ICollection<tbl_22_Spektr> tbl_22_Spektr { get; set; }
        public virtual ICollection<tbl_38_OtherMaterials> tbl_38_OtherMaterials { get; set; }
        public virtual ICollection<tbl_39_Metals> tbl_39_Metals { get; set; }
        public virtual ICollection<tbl_40_Paints> tbl_40_Paints { get; set; }
    }
}
