//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_40_Paints
    {
        public tbl_40_Paints()
        {
            this.tbl_26_Pigments = new HashSet<tbl_26_Pigments>();
        }
    
        public int PaintId { get; set; }
        public int MaterialId { get; set; }
        public string PaintName { get; set; }
        public string PaintRemark { get; set; }
    
        public virtual ICollection<tbl_26_Pigments> tbl_26_Pigments { get; set; }
        public virtual tbl_37_Material tbl_37_Material { get; set; }
    }
}
