//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_30_AuthorType
    {
        public tbl_30_AuthorType()
        {
            this.tbl_11_AuthorPictures = new HashSet<tbl_11_AuthorPictures>();
        }
    
        public int AuthorTypeId { get; set; }
        public string AuthorTypeName { get; set; }
        public string AuthorSubTypeName { get; set; }
        public string AuthorParentType { get; set; }
    
        public virtual ICollection<tbl_11_AuthorPictures> tbl_11_AuthorPictures { get; set; }
    }
}
