//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_35_ArtWorkGenre
    {
        public int ArtWorkGenreId { get; set; }
        public int ArtWorkId { get; set; }
        public string ArtWorkGenreName { get; set; }
        public string ArtWorkGenreDescription { get; set; }
    
        public virtual tbl_14_ArtWork tbl_14_ArtWork { get; set; }
    }
}
