//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int IDUserRole { get; set; }
        public int IDRole { get; set; }
        public int IDUser { get; set; }
    
        public virtual tbl_1_User tbl_1_User { get; set; }
        public virtual tbl_2_Roles tbl_2_Roles { get; set; }
    }
}
